os: osx
language: ruby
before_cache:
  - brew cleanup
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_install:
  - |
        # Install `ShellCheck`.
        #
        # ShellCheck is required for testing and
        # is included with Travis's Ubuntu builds,
        # so it only needs to be installed for the
        # macOS ones.
        if [ "$TRAVIS_OS_NAME" = "osx" ]; then
          brew install shellcheck
      fi
addons:
  homebrew:
    update: true
    brewfile: true
script:
  # - shellcheck $(grep -rl '"^#!/bin/sh\|^#!/bin/bash\|^#!/usr/bin/env bash' ./ | g
  - shellcheck ./.brew/brew.sh
  - shellcheck ./.setup/bootstrap.sh
