os: osx
language: ruby
before_cache:
  - brew cleanup
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
addons:
  homebrew:
    update: true
    brewfile: true
script:
  # - shellcheck $(grep -rl '"^#!/bin/sh\|^#!/bin/bash\|^#!/usr/bin/env bash' ./ | g
  # - shellcheck ./.brew/brew.sh
  # - shellcheck ./.setup/bootstrap.sh
